# Generated by Django 5.1.1 on 2025-01-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("cashier", "Cashier"), ("manager", "Manager")],
                default="cashier",
                max_length=50,
                null=True,
            ),
        ),
    ]
