# Generated by Django 5.1.1 on 2025-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_is_active"),
        ("users", "0003_customuser_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="branch",
        ),
        migrations.AddField(
            model_name="customuser",
            name="branches",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="users", to="branches.branch"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cashier", "Cashier"),
                    ("manager", "Manager"),
                    ("admin_manager", "Admin Manager"),
                ],
                default="cashier",
                max_length=50,
                null=True,
            ),
        ),
    ]
