# Generated by Django 5.1.1 on 2025-01-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0006_remove_transaction_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card")], max_length=10
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="sales.transaction",
                    ),
                ),
            ],
        ),
    ]
