# Generated by Django 5.1.1 on 2025-01-12 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("sales", "0008_transaction_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="sales.transaction",
            ),
        ),
    ]
