# Generated by Django 5.1.1 on 2024-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paypalpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripepayment",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
