# Generated by Django 5.1.1 on 2025-01-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_card_payment_payment_cash_payment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="total_amount",
        ),
    ]
