# Generated by Django 5.1.1 on 2025-01-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_rename_amount_payment_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="total_amount",
            new_name="total_payment",
        ),
    ]
