# Generated by Django 5.1.1 on 2025-01-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_rename_total_amount_payment_total_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cash_returned",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
