# Generated by Django 5.1.1 on 2025-01-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_payment_cash_returned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="cash_returned",
            new_name="balance_returned",
        ),
    ]
