# Generated by Django 5.1.1 on 2025-01-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="name",
            new_name="code",
        ),
    ]
