# Generated by Django 5.1.1 on 2025-01-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0002_product_created_by_product_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
