# Generated by Django 5.1.1 on 2025-01-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0003_product_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="images",
            new_name="image",
        ),
    ]
