# Generated by Django 5.1.1 on 2025-01-15 18:14

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0004_rename_images_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to="images/",
            ),
        ),
    ]
