# Generated by Django 5.1.1 on 2025-01-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
