# Generated by Django 5.1.1 on 2025-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0008_stockinput"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
