# Generated by Django 5.1.1 on 2025-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0009_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
