# Generated by Django 5.1.1 on 2025-04-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_is_active"),
        ("inventory_management", "0010_alter_product_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="branches.branch",
            ),
        ),
    ]
