# Generated by Django 5.1.1 on 2025-08-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="modules",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="rbac.module"
            ),
        ),
    ]
