# Generated by Django 5.1.1 on 2025-01-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_transaction_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
