# Generated by Django 5.1.1 on 2025-01-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_transaction_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionitem",
            old_name="price",
            new_name="total_amount",
        ),
    ]
