# Generated by Django 5.1.1 on 2025-01-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_rename_price_transactionitem_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
    ]
