# Generated by Django 5.1.1 on 2025-01-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_transaction_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionitem",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
