# Generated by Django 5.1.1 on 2025-01-19 20:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_alter_transaction_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_transaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
