# Generated by Django 5.1.1 on 2025-01-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_transaction_updated_at_transaction_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
