# Generated by Django 5.1.1 on 2025-04-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_alter_transaction_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                default="dd4a7dd9-72bc-41b0-9110-77920df978a9",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="created_transaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
