# Generated by Django 5.1.1 on 2025-04-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_is_active"),
        ("sales", "0014_alter_transaction_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="branches.branch",
            ),
            preserve_default=False,
        ),
    ]
