# Generated by Django 5.1.1 on 2025-06-23 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_transaction_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                default="dd4a7dd9-72bc-41b0-9110-77920df978a9",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_transaction",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_by",
            field=models.ForeignKey(
                default="dd4a7dd9-72bc-41b0-9110-77920df978a9",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_transaction",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
